id: 0b2609515d7544dd8aa9e1998328e94f
initial_creation_type: ocr
source_metadata:
  volumes:
    b5c7c58c73644ec096455bda9202e3f0:
      base_file: v011.txt
      image_group_id: I1PD95856
      title: ''
      total_pages: 2107
      volume_number: 11
